### ISSUE TITLE
Finishing up V1

### ISSUE THREAD

**Issue by mtalcott** [promantek/style#1]
Here's my feedback on some things, now that my eyes have been off the project for a while. For some of these, @serogers will probably need to help out. Some of them also may not require action, but just respond to them and let me know what you think!

- [x] We're currently mixing `col-md-X` and `col-sm-X` bootstrap classes. This has the effect of collapsing different parts of the style guide into a single column at different page widths, which we don't want. Let's change to use `col-sm-X` classes everywhere, as it results in good behavior for our content (only collapse into a single column at small screen sizes - 768px - rather than 992px with `col-md-X`.
- [x] The bootstrap grid layout is 12 columns wide. There are many places that don't stretch across the full width. Change these to add up to 12 columns wide. Also, remove nested columning, where possible.
  * [x] `col-md-8` in the "Paragraphs" section
  * [x] `col-md-9 col-md-offset-1` *within* a `col-md-10` in the "Fonts" section
  * [x] `col-md-5 col-md-offset-1` in the "Non-web assets" section
  * [x] `col-sm-8` under "Swatches"
  * [x] Double-check for any others I missed
- Nice work on the Color Contrast Checker link!
- [x] We're indenting some, but not all, of our `h3` elements. Under "Presentations", "Powerpoint" is indented, but under "Forms/Inputs" we're not. We should be consistent here. If we think that certain sub-headers should be indented, let's do that everywhere, even for sections without content currently.
- [x] The "Dark" color ratio wheel seems way off. Would we really make something with that much orange and blue? I was imagining that these would be representative of someone with really, really bad eyesight looking at our web page, application, PDFs, sales demos, etc. They should guide people for how frequently to use certain colors. We may need more than two here, but let's create them based off of some of our content we've already created (the first one I was aiming to look like our current style guide).
- [x] Let's make the style guide have our new, fancy favicon!
- "In progress" sections
  - [x] are marked with "In progress" followed by an hourglass, the other way around, and also a "Coming soon." Let's standardize.
  - [x] don't seem clearly differentiated from finished parts. Let's add strikethroughs (or some other kind of obvious marking, other than opacity) to these parts.
- [x] It seems like we're using two methods of communicating "subtle" text. We have the one specified explicitly under "Body", but also the small ones detailing font face, size, and color. Are these different use cases? If not, I'd like to choose one (I prefer the small one with font details).
- [x] The Word template only has a single file in it. Do we need to make it a .zip file?

**Comment by trickssterr** [comment]
Easy things (slash no argument/questions): 

Done: col-sm vs. col-md

Done: h3 elements: indented. I think the guideline here could be indent h3s when they're inline, vertically, with the main content, but when they're broken out horizontally (like in the Color Ratios section), no need to indent. 

Done: Subtle text. I agree with your point; no argument here!

Done: In Progress changes. 

Things with questions: 

• Bootstrap grid: Do you mean add in empty <div>s, then? Also, when I was quickly reading up I caught this on Bootstrap nesting: http://getbootstrap.com/css/#grid-nesting. Now that I'm re-reading it I see I wasn't doing it quite right anyway, but wanted to clarify the "(it is not required that you use all 12 available columns)" comment there. I'm totally cool with it, I just want to make sure I'm on the same page. 

• Color ratio wheel: The "dark" version was intended as a "reverse type" type example (like the dark orange background slides on Powerpoint). But maybe we need to hash that out a bit to align our expectations. I'm really not that familiar with the things, to be honest. I can go hunt for some more examples if needed.

• Where does the favicon icon live in this github world? 

• Word template zip: That's a .zip to stay consistent with the Powerpoint and Font zip files, and to keep the name the same in case we do add more files, BUT I'm not attached (har) to it either way.

**Comment by mtalcott** [comment]
> Bootstrap grid: Do you mean add in empty divs, then? Also, when I was quickly reading up I caught this on Bootstrap nesting: http://getbootstrap.com/css/#grid-nesting. Now that I'm re-reading it I see I wasn't doing it quite right anyway, but wanted to clarify the "(it is not required that you use all 12 available columns)" comment there. I'm totally cool with it, I just want to make sure I'm on the same page.

We don't *have* to use all of them, but it looks kind of funny if the content doesn't stretch all the way across the page. It also looks funny because we have different content that spans 8, 5, and 9 columns out of 12.

Let's use all 12 unless we have a reason to keep some space on the right side, and not nest column layouts unless we need to.

> Color ratio wheel: The "dark" version was intended as a "reverse type" type example (like the dark orange background slides on Powerpoint). But maybe we need to hash that out a bit to align our expectations. I'm really not that familiar with the things, to be honest. I can go hunt for some more examples if needed.

Okay, let's talk about it today and see what we want to do. If there are clearer ways to visually communicate color ratios, I'm all for them! (Maybe like "take a look at this PDF I already made")

> Where does the favicon icon live in this github world?

@serogers, could you figure out how to hook this up?

> Word template zip: That's a .zip to stay consistent with the Powerpoint and Font zip files, and to keep the name the same in case we do add more files, BUT I'm not attached (har) to it either way.

That makes sense. Let's leave it as a .zip!

**Comment by trickssterr** [comment]
I went through and standardized the columns and fixed some places where it didn't look right. I'm sticking with col-sm-8 for paragraphs of text. Anything wider gets hard to read. Let me know if I missed any or if something looks wonky?

**Comment by serogers** [comment]
Favicon has been updated!

**Comment by trickssterr** [comment]
fancy!

**Comment by mtalcott** [comment]
Nice!

col-sm-8 looks great to me. Nice job on all of the fixes!

One other thing: Let's remove that link for the temporary style guide up top. We can say instead "This is still a work in progress. Those areas are marked. Use the rest of the guide to help bring a consistent look and feel to Trakstar!" or something.

We'll chat about color ratio wheels, but they're fine for now.

After those changes, I'll send an email so we can share this with everyone!

**Comment by trickssterr** [comment]
Done!

**Comment by mtalcott** [comment]
![awwyeah](https://cloud.githubusercontent.com/assets/354599/9502882/a6982b3e-4be8-11e5-8039-8f1d3078f266.jpg)

I'll work on an email after lunch!
